### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(CMG_2026)
add_subdirectory(CMG_2026Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    CMG_2026plugin
    CMG_2026Contentplugin
    QtQuickDesignerComponents)